
services:
  postgres:
    image: postgres
    container_name: kucharka_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5434:5432"
    volumes:
      [postgres_data:/var/lib/postgresql/data]

volumes:
  postgres_data: