name: Deploy to Raspberry Pi

on:
    push:
        branches: [ main ]

    workflow_dispatch: 

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Check out the repository
              uses: actions/checkout@v3

            - name: Pulls latest changes on Raspberry Pi
              run: |
                cd /home/admin/intranet
                git pull origin master

            - name: Install base proxy server
              run: |
                cd /home/admin/intranet
                npm i

            - name: Install kucharka server
              run: |
                cd /home/admin/intranet
                npm i

    deploy:
        runs-on: self-hosted
        needs: build

        steps:
            - name: Restart Pi
              run: sudo reboot
    